### PR TITLE
Optibp calibration

### PR DESCRIPTION
**Pull request by SebaMutuku**

### CODE REVIEW

**Review by dubdabasoduba — CHANGES_REQUESTED** [review]
Fix all the code quality issues highlighted by codacy

**Comment by SebaMutuku** [comment]
@dubdabasoduba please add `optibp_main` and `brazil_main` branches to codacy check. I don't have the permission to do that

**Comment by dubdabasoduba** [comment]
> @dubdabasoduba please add `optibp_main` and `brazil_main` branches to codacy check. It's based on this PR #892

They are now enabled. Please review

**Comment by SebaMutuku** [comment]
@dubdabasoduba not yet. Please merge the PR there.

**Pull request merged**
