### PR TITLE
Update the sync filter

### PR DESCRIPTION
**Pull request by dubdabasoduba**

### CODE REVIEW

**Review by junaidwarsivd — COMMENTED** [review]
its base class is expecting  public List<String> getExtraSettingsParameters() 
there is no such method as String getExtraStringSettingsParameters() @dubdabasoduba

**Comment by dubdabasoduba** [comment]
> its base class is expecting public List getExtraSettingsParameters()
> there is no such method as String getExtraStringSettingsParameters() @dubdabasoduba

Please check https://github.com/opensrp/opensrp-client-core/blob/9cc7955e57846de4a992ced5120be5d259ebab0e/opensrp-app/src/main/java/org/smartregister/SyncConfiguration.java#L159

**Comment by junaidwarsivd** [comment]
but the added dependency in the project is org.smartregister:opensrp-client-core:4.3.17-SNAPSHOT@aar
and it does'nt have that method please check 
https://github.com/opensrp/opensrp-client-core/blob/v4.3.17-SNAPSHOT/opensrp-app/src/main/java/org/smartregister/SyncConfiguration.java

**Comment by dubdabasoduba** [comment]
> but the added dependency in the project is org.smartregister:opensrp-client-core:4.3.17-SNAPSHOT@aar
> and it does'nt have that method please check
> https://github.com/opensrp/opensrp-client-core/blob/v4.3.17-SNAPSHOT/opensrp-app/src/main/java/org/smartregister/SyncConfiguration.java

the core version on the app right now is `4.3.22-SNAPSHOT`

**Review by junaidwarsivd — APPROVED** [review]

**Pull request merged**
